### ISSUE TITLE
Launch tracking

### ISSUE THREAD

**Issue by kytrinyx** [exercism/awk#1]
This issue helps keep track of the tasks you're working on towards launching this track.

The next steps are:

- [x] [Join our community](https://exercism.org/docs/building/tracks/new/join-our-community)
- [x] [Select programming language variant](https://exercism.org/docs/building/tracks/new/select-programming-language-variant) (if applicable)
- [x] [Select testing framework](https://exercism.org/docs/building/tracks/new/select-testing-framework)
- [x] [Add the first exercise](https://exercism.org/docs/building/tracks/new/add-first-exercise)
- [x] [Add initial exercises](https://exercism.org/docs/building/tracks/new/add-initial-exercises)
- [x] [Setup Continuous Integration](https://exercism.org/docs/building/tracks/new/setup-continuous-integration)
- [x] [Prepare for launch](https://exercism.org/docs/building/tracks/new/prepare-for-launch)
    - [x] request track icon
    - [x] add `docs/*.md`
    - [x] add `exercises/shared/.docs/*.md`
    - [x] track metadata in config.json
- [x] [Find Maintainers](https://exercism.org/docs/building/tracks/new/find-maintainers)
- [x] [Launch!](https://exercism.org/docs/building/tracks/new/launch)
- [x] [Implement tooling](https://exercism.org/docs/building/tracks/new/implement-tooling)
    - [x] write the test runner
    - [x] test runner is live 
- [x] [Prepare for open source contributions from strangers](https://exercism.org/docs/building/tracks/new/prepare-for-contributions)

Once you've finished a task, you can check them in this list.

## Questions

Please ask if you have any questions or if anything is confusing!

**Comment by ErikSchierboom** [comment]
Great news that you're working on this @glennj! Let me know if you need any help or if anything is lacking.

**Comment by IsaacG** [comment]
It looks like @glennj and I are the current stand ins for maintainers.

I believe there's no current blockers to accepting open source contributions. @glennj, are those items completed? Can this issue be resolved?

**Comment by glennj** [comment]
You're right @IsaacG
